### ISSUE TITLE
Не перпедавать argv в функции логики

### ISSUE THREAD

**Issue by olgapshen** [DarkHunteR73/MaxiOracleTask#24]
https://github.com/DarkHunteR73/MaxiOracleTask/blob/5c47c69ef99ce206ac491be53aa27a4bd99c2dae/main.cpp#L22

Вот тут https://github.com/DarkHunteR73/MaxiOracleTask/blob/5c47c69ef99ce206ac491be53aa27a4bd99c2dae/dal.h#L28 нужно передать параметр сортировки через логические переменные.

**Comment by olgapshen** [comment]
По идеи должно быть так:

```
enum SortingType {
    SortType_ByAddress
    ,SortType_ByCount
};

class dataAccessLayer {
...
    vector<Record> getSortedQuery(SortingType sortingType);
...
}
```

**Comment by DarkHunteR73** [comment]
как-то так?  b0c2be43279ddcc14eeb014379ba5c9a637290b6

**Comment by olgapshen** [comment]
Сделала Pull Request Review: https://github.com/DarkHunteR73/MaxiOracleTask/pull/31
