### ISSUE TITLE
Параметр сортировки

### ISSUE THREAD

**Issue by olgapshen** [DarkHunteR73/MaxiOracleTask#8]
Сделать возможным передать при запуске программы через ARGV параметр сортировки

* s - по адресам
* d - по количеству

В main.cpp отсортировать полученный из dal.h вектор со структурами в соответствии с переданным параметром.
По умолчанию сортировать по адресам.
Сортировка методом пузырьков.

**Comment by DarkHunteR73** [comment]
abeaa88adb5345c1049269933e6f31982c380a4e

**Comment by olgapshen** [comment]
Молодец.
