### ISSUE TITLE
Оформить запрос в базе в виде отображения

### ISSUE THREAD

**Issue by olgapshen** [DarkHunteR73/MaxiOracleTask#9]
https://github.com/DarkHunteR73/MySQL_Task_db/blob/f37f6c9b1b1020a8e43e197d5d7efd42b6a1ddca/task_query.sql#L1

Создать отображение (View) в базе с этим запросом и в C++ тянуть информацию из View.

**Comment by olgapshen** [comment]
Привет! Молодец! Но перед закрытием задачи, думаю лучше дать более подходящее имя отображению чем `VIEW1`.
Например `VIEW_ADDRESSES` или что то вроде этого.

Ещё момент, старайся не экспортировать каждый раз скрипт схемы, а править его руками, что бы:
1. Oracle туда случайно не засунул лишнего
2. Не нарушался порядок строк для insert-ов, а то у тебя там строки в разброс пошли
3. Не было так много изменений каждый раз
4. Ты точно знал что есть в скрипте, что бы ты ощёщал над ним полный контроль

То есть по сути именно ты пишешь скрипт, а Oracle его интерпретирует.
Иначе получается что вы с Oracle-ом по очереди его пишите ) Тогда Oracle-у тоже надо создать пользователя в проекте и научить его делать Pull Request-ы )))

**Comment by DarkHunteR73** [comment]
55364ce0e9ad7afb54dd79f5674f5791a60b8e7d

**Comment by olgapshen** [comment]
Молодец!
